{
  "name": "My Workflow",
  "on": {
    "push": {
      "branches": [
        "main"
      ]
    }
  },
  "jobs": {
    "build": {
      "runs_on": "ubuntu-latest",
      "steps": [
        {
          "name": "sonarqube Step",
          "run": "sonar-scanner"
        },
        {
          "name": "A",
          "run": "echo 'A'"
        },
        {
          "name": "A",
          "run": "echo 'A'"
        },
        {
          "name": "maven",
          "run": "echo 'maven'"
        },
        {
          "name": "A",
          "run": "echo 'A'"
        },
        {
          "name": "B",
          "run": "echo 'B'"
        }
      ]
    }
  }
}