{
  "name": "My Workflow",
  "on": {
    "push": {
      "branches": [
        "main"
      ]
    }
  },
  "jobs": {
    "build": {
      "runs_on": "ubuntu-latest",
      "steps": [
        {
          "name": "sonarqube Step",
          "run": "sonar-scanner"
        },
        {
          "name": "maven Step",
          "run": "mvn package"
        },
        {
          "name": "sonarqube Step",
          "run": "sonar-scanner"
        }
      ]
    }
  }
}